SELECT
    ED_C.ID,
    ED_C.GENOTYPE,
    ED_P.GENOTYPE AS PARENT_GENOTYPE
FROM
    ECOLI_DATA ED_C
INNER JOIN
    ECOLI_DATA ED_P ON ED_C.PARENT_ID = ED_P.ID
WHERE
    ED_C.GENOTYPE & ED_P.GENOTYPE = ED_P.GENOTYPE
ORDER BY
    ED_C.ID;